### ISSUE TITLE
Error running router

### ISSUE THREAD

**Issue by thesuhas** [dicej/isyswasfa#3]
I'm trying to run the router and there seems to be an issue with the imports/exports of echo.

<img width="541" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/05c84f28-0d7a-4990-aba1-3556e71e0144">

Echo itself seems to work fine so I'm assuming there is something wrong with the world as it defines the imports/exports.

**Comment by thesuhas** [comment]
I've commented out echo and it seems like now the error is that `hash-all` has the wrong type. Importing components seems to be failing

**Comment by dicej** [comment]
Hi @thesuhas.  Thanks for reporting this.

Have you tried running `cargo test --release test::router`, and if so, does it pass?  It seems to be working on my end.  Also, I just noticed that I accidentally left some debug code in that test which writes the composed component to `/tmp/composed.wasm`.  I ran that using `./target/release/isyswasfa serve /tmp/composed.wasm` and it seems to work fine.

**Comment by thesuhas** [comment]
Trying to run the test fails with the following error:
<img width="871" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/dceda8d1-4cf1-4012-ae69-22eb37df70b2">

**Comment by thesuhas** [comment]
On doing a bit more digging, I see that a `tmp` directory never gets created for me. I've also tried making my own components that imported other components, I get the same issue.

**Comment by dicej** [comment]
The issue you hit when building `componentize-py` might be due to some kind of change in the compiler that ships with macOS 14; I'll have to investigate that separately.

Meanwhile, can you try checking out the `no-python` branch I just pushed and run `cargo test --release test::router` with that?  I've commented out the Python parts, so it should work this time.  :crossed_fingers:

**Comment by thesuhas** [comment]
It now passes the tests!
<img width="973" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/bdeef0dc-24b6-4321-93cc-2a82a02ffd60">

But it still throws the same error?
<img width="1157" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/d52ef51d-f5c2-4ee5-8890-b8b3c186de0e">
I've detailed the steps in the screenshot. Am I missing something?

**Comment by dicej** [comment]
`router.wasm` is not useful by itself -- it needs to be composed with all the other components it is routing to before it can be executed.  That's what the test does: https://github.com/dicej/isyswasfa/blob/df9a153fafbbdf532d811bdc53e61ff7368e4898/test/src/lib.rs#L895-L1006.  You'll need to build the other components and use `wasm-tools compose` to compose them like the test does.

BTW, please make sure you're using the `wasm-tools` built from the submodule in this repo.

**Comment by thesuhas** [comment]
Let's say I want to compose both `echo` and `hash_all`. I would need to run the modified `wasm-tools compose` with multiple root components.
`./wasm-tools/target/release/wasm-tools compose echo.wasm hash_all.wasm -d router.wasm -o composed_router.wasm` throws this error: 
<img width="390" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/893b1666-aa52-4493-be6b-8f744130552b">
I assume this is the case because `wasm-tools compose` lets us compose only a single component at once.
Hence, I tried first composing `echo` and then adding `hash_all` to the composed component. I get this error then: 
<img width="923" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/2ccc6d30-130f-4e75-8a2b-9c18b81ec29a">
What would be the right way to do this?

**Comment by dicej** [comment]
The CLI interface for `wasm-tools compose` only handles simple cases, and I don't think it will handle this case.  More advanced cases require either using the Rust library API (which is what the test I referenced does) or using a configuration file.

My advice would be to start by reading [the docs](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose), especially the [configuration docs](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasm-compose/CONFIG.md) and see if you can translate [this code that uses the Rust API](https://github.com/dicej/isyswasfa/blob/df9a153fafbbdf532d811bdc53e61ff7368e4898/test/src/lib.rs#L925-L994) into a configuration file, which you can then reference using the CLI.

BTW, I'm not really an expert on `wasm-compose`, so you might have better luck opening an issue on the `wasm-tools` repo and/or posting your questions on https://bytecodealliance.zulipchat.com.

**Comment by thesuhas** [comment]
Thanks! I missed the compose step, overlooked that. I do still have one issue though. I was able to compose `echo` and the `router` but when I try to compose `echo` and `hash_all` to the `router`, I get the following error:
<img width="1189" alt="image" src="https://github.com/dicej/isyswasfa/assets/54014218/9141f96f-6800-44b1-9dbe-77b8fcf8b47e">

**Comment by thesuhas** [comment]
> The CLI interface for `wasm-tools compose` only handles simple cases, and I don't think it will handle this case. More advanced cases require either using the Rust library API (which is what the test I referenced does) or using a configuration file.
> 
> My advice would be to start by reading [the docs](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose), especially the [configuration docs](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasm-compose/CONFIG.md) and see if you can translate [this code that uses the Rust API](https://github.com/dicej/isyswasfa/blob/df9a153fafbbdf532d811bdc53e61ff7368e4898/test/src/lib.rs#L925-L994) into a configuration file, which you can then reference using the CLI.
> 
> BTW, I'm not really an expert on `wasm-compose`, so you might have better luck opening an issue on the `wasm-tools` repo and/or posting your questions on https://bytecodealliance.zulipchat.com.

Will do, thanks!

**Comment by dicej** [comment]
Also, I should note that the new, better way to do composition is [WAC](https://github.com/bytecodealliance/wac), but I don't have much experience with it, so I'm not sure how to apply it in this case.

**Comment by thesuhas** [comment]
Thanks! I don't think I can use that for the HTTP 3.0 interface though right? Not yet at least

**Comment by dicej** [comment]
Oh, and the "kebab case" errors are due to the component model constraint that names must use `kebab-case` rather than `snake_case`, and I think `wasm-compose` expects the filenames to respect that constraint as well.

**Comment by thesuhas** [comment]
Oh that fixed it! Thank you so much! The error message was confusing with the offset as I assumed it was in the `.wasm` file and not the name of the file itself.

**Comment by dicej** [comment]
> Thanks! I don't think I can use that for the HTTP 3.0 interface though right? Not yet at least

In theory WAC should be able to handle the `wasi:http@0.3.0-draft` components produces by `isyswasfa` since `isyswasfa` doesn't rely on any extensions to the component model (just certain conventions), but there could be bugs or limitations that prevent it, yes.

One more important thing to note: `isyswasfa` is a temporary project intended to work around current limitations in the component model and WASI, and I don't plan to support it in the long term.  In fact, I'm working hard to make it obsolete by working with Luke Wagner to define and implement async support for the component model, which will be the foundation for a proper implementation of `wasi:http@0.3.0`, etc.  Once that work has been merged, I'll deprecate `isyswasfa` and invite users to switch to the real thing.
